### ISSUE TITLE
OC-Accelerator > Admin > Token lifetime

### ISSUE THREAD

**Issue by coding-frank** [ordercloud-api/oc-accelerator#32]
AccessToken expires and user gets logged out after 5 minutes. We expect the token to be refreshed within Refresh Token Duration.

<img width="702" alt="image" src="https://github.com/user-attachments/assets/b6ff70b8-708a-4856-bcbe-cb40b2978ad2">

**Comment by robertsoniv** [comment]
@coding-frank this issue was addressed in the latest version of the ordercloud-react package. Every request will now verify the token via axios interceptors. If the token is no longer valid and there is a stored refresh token, it will automatically refresh before making the next request. Keep in mind, you will need to check the "keep me logged in" box on the login form.

**Comment by coding-frank** [comment]
@robertsoniv I updated @rwatt451/ordercloud-react to version 0.0.24.
Now I see nearly on all requests 403 CORS errors. 

"Keep me logged in" is checked
<img width="1006" alt="image" src="https://github.com/user-attachments/assets/da931113-4b0a-4870-98fe-62bb67d92b7a">

**Comment by robertsoniv** [comment]
This was one of the issues we did run into while updating the package. We had hoped it wouldn't affect others when updating their versions. The fix did involve some additional changes on the admin application as well, were you able to merge those in?

If not, I can try and help you if you happen to have a public branch I can pull down. We did introduce a "breaking" change in the package that was addressed in the latest updates to the oc-accelerator admin app.

**Comment by robertsoniv** [comment]
If you are able to, we recommend that you merge the latest from the main branch of oc-accelerator into your own. If the problem persists, please do come back and report.

Apologies for the inconvenience, our fix for the token refresh in version 0.0.24 also included some other improvements that required a small refactor of some shared code in the admin application. Instead of allowing the usual "enabled" prop in tanstack query configs, we now provide a "disabled" prop that is combined with the primary "isAuthenticated" check on first page load.

**Comment by coding-frank** [comment]
@robertsoniv Merge from your latest branch w'ont work as we have massively modified some components and we are using only the admin folder in a mono repo.

I saw the change from enable to disabled, but still see this CORS issue.
Do I have to update any other library as well?
